### ISSUE TITLE
Get error in compile

### ISSUE THREAD

**Issue by djgel** [Darkwulf183/Marlin-2.0.x-Bugfix-LVGL-Ui-pre-defined-update.cbd-and-assets#2]
Hi, get this  error , can you help me ?
Error: Build environment 'LPC1769' is incompatible with BOARD_CHITU3D_V6. Use one of these: chitu_f103, chitu_v5_gpio_init

**Comment by Darkwulf183** [comment]
Good morning,
A: It's not an issue. Then why are you opening one? 
B: Everything is described in the video on YouTube.
C: I don't edit issues on Github. Only on Youtube.
It's your fault. You have to change in the platformio.ini 
default_envs = LPC1769 to default_envs = chitu_f103.
Then it will compile. 
Oh, and you also wrote the issue into the wrong repository, so it will be closed directly.

Thanks and have a nice week.
